[package]
name = "rosu-pp"
version = "0.2.0"
authors = ["MaxOhn <ohn.m@hotmail.de>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/MaxOhn/rosu-pp"
documentation = "https://docs.rs/rosu-pp/"
description = "osu! difficulty and pp calculation for all modes"
keywords = ["osu", "pp", "stars", "async"]

[features]
default = ["osu", "taiko", "fruits", "mania", "no_leniency"]

# game modes
osu = []
taiko = []
fruits = []
mania = []

# osu!standard version
all_included = []
no_leniency = []
no_sliders_no_leniency = []

# async version
async_std = ["async-std"]
async_tokio = ["tokio"]

[dependencies.async-std]
version = "1.9"
optional = true

[dependencies.tokio]
version = "1.2"
optional = true
default-features = false
features = ["io-util"]

[dev-dependencies.tokio]
version = "1.2"
features = ["fs", "rt-multi-thread"]